site_name: Data Science
nav:
  - Início: index.md
  - Sobre: sobre.md
  - 1.Estatistica:
    - Introdução: 1_estatistica/Introducao_estatistica.md
  - 2.Machine Learning: 2_machine_learning/configuracao.md
  - Repositório de Projetos:
    - Modelagem:
      - EDA
theme:
  name: material 
  custom_dir: 'cinder'
  colorscheme: dracula
  hljs_languages:
    - python
  features:
    - navigation.tabs
    - navigation.indexes
plugins:
  - search
  - mkdocs-jupyter  # Movido para o final
markdown_extensions:
  - admonition
  - tables
  - fenced_code
  - codehilite
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css  # Opcional (se quiser usar KaTeX)
