site_name: Data Science
nav:
  - Início: index.md
  - 1.Estatistica:
    - Introdução: 1_estatistica/Introducao_estatistica.md
    - 1.1_testes_de_hipotese:
      - 1.1.1. Teste_Hipotese: 1_estatistica/1.1_testes_de_hipoteses/1.1.1_Teste_Hipoteses.md
      - 1.1.2. O_que_sao_testes_de_hipotese: 1_estatistica/1.1_testes_de_hipoteses/1.1.2_O_que_sao_os_ts.md
      - 1.1.3. Aplicacoes_testes_de_hipotese: 1_estatistica/1.1_testes_de_hipoteses/1.1.3_Aplicacao_teste_de_hipotese.ipynb
      - 1.1.4. Aplicacoes_intervalos_de_confianca: 1_estatistica/1.1_testes_de_hipoteses/1.1.4_Aplicacao_intervalos_de_confianca.ipynb
      - 1.1.5. O_que_e_p_valor: 1_estatistica/1.1_testes_de_hipoteses/1.1.5_O_que_e_p_valor.md
      - 1.1.6. Aplicacao_Permutacional_Test: 1_estatistica/1.1_testes_de_hipoteses/1.1.6_Aplicacao_Permutacion_test.ipynb
      
  - 2.Machine Learning:
      - Introdução: 2_machine_learning/Introducao_machine_learning.md
      - 2.1_Crisp-DM:
        - 2.1.1 Crisp-DM: 2_machine_learning/2.1_CRISP-DM/2.1.1_CRISP-DM.md
        - 2.1.2 Pre_treinamento: 2_machine_learning/2.1_CRISP-DM/2.1.2_Pre_treinamento.md
        - 2.1.3_Treinamento: 2_machine_learning/2.1_CRISP-DM/2.1.3_Treinamento.md
        - 2.1.4_Pos_treinamento: 2_machine_learning/2.1_CRISP-DM/2.1.4_Pos_treinamento.md

  - 3.Machine Learning Engineer:
      - Introdução: 3_machine_learning_engineer/Introducao_machine_learning_engineer.md

  - 4.Analise de dados:
      - Introdução: 4_analise_dados/Introducao_analise_dados.md

  - 5.Ferramentas:
      - Introdução: 5_Ferramentas/Introducao_Ferramentas.md
      - 5.1 Banco de dados:
        - 5.1.1 MongoDB: 5_Ferramentas/5.1_Bancos_de_Dados/5.1.1_MongoDB.md
        - 5.1.2 MongoDB Crud: 5_Ferramentas/5.1_Bancos_de_Dados/5.1.2_MongoDB_crud.md
        - 5.1.3 MongoDB Operadores: 5_Ferramentas/5.1_Bancos_de_Dados/5.1.3_MongoDB_operadores.md
      - 5.2 git: 5.2_Git.md
      - 5.4 Docker: 5_Ferramentas/5.3_Docker.md
      - 5.5 Cookiecutter: 5_Ferramentas/5.5_Cookiecutter.md
      - 5.6 Streamlit: 5_Ferramentas/5.6_Streamlit_Dashboard.md
      - 5.7 Minha_Estrutura: 5_Ferramentas/5.7_Minha_Estrutura.md
      - 5.8 Terminal: 5_Ferramentas/5.8_Terminal.md
      - 5.9 mkdocs: 5_Ferramentas/5.9_mkdocs.md

theme:
  name: material 
  custom_dir: 'cinder'
  colorscheme: dracula
  hljs_languages:
    - python
  features:
    - navigation.tabs
    - navigation.indexes
plugins:
  - search
  - mkdocs-jupyter  # Movido para o final
markdown_extensions:
  - admonition
  - tables
  - fenced_code
  - codehilite
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css  # Opcional (se quiser usar KaTeX)
